name: py310_caddseminar2024
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rdkit
  - jupyter
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - xgboost
  - jupyter_contrib_nbextensions
  - py3dmol
  - ca-certificates
  - certifi
  - openssl
