name: py310_caddseminar2024
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rdkit
  - jupyter
  - jupyterlab
  - pandas
  - biopandas
  - numpy
  - matplotlib
  - nglview
  - scipy
  - scikit-learn
  - xgboost
  - py3dmol
  - ca-certificates
  - biopython
  - MDAnalysis
  - openssl
